Vagrant.configure("2") do |config|
#  config.ssh.insert_key = true
#  config.vm.box = "centos/stream9"
  config.vm.box = "fedora/41-cloud-base"
  ["web-a","web-b","lb","db"].each do |deploy|
    config.vm.define "#{deploy}" do |node|
      node.vm.hostname = "#{deploy}"
    end
  end
  config.vm.provider "libvirt" do |lv|
#    lv.random_hostname = true
#    lv.default_prefix = "lab"
    lv.storage_pool_name = "personal"
    lv.driver = "qemu"
    lv.qemu_use_agent = true
    lv.channel :type => "unix", :target_type => "virtio", :target_name => "org.qemu.guest_agent.0"
    lv.memory = 512
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant_libvirt_bootstrap.yml"
  end
end#
