REQUIRED_PLUGINS = %w(vagrant-libvirt ansible vagrant-hostsupdater vagrant-faster)
exit unless REQUIRED_PLUGINS.all? do |plugin|
  Vagrant.has_plugin?(plugin) || (
    puts "The #{plugin} plugin is required. Please install it with:"
    puts "$ vagrant plugin install #{plugin}"
    false
  )
end

nodes = [
  # {:name => "lb1", :ip => "192.168.121.10"},
  {:name => "wb1", :ip => "192.168.121.20", :cpus => 2, :memory => 2048},
  {:name => "wb2", :ip => "192.168.121.30", :cpus => 2, :memory => 2048}
]

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.box = "centos/stream9"
  # config.vm.box = "fedora/41-cloud-base"
  config.ssh.insert_key = false
  nodes.each do |node|
    config.vm.define node[:name] do |deploy|
      deploy.vm.hostname = node[:name]
      deploy.vm.network :private_network, :ip => node[:ip]
      config.vm.provider :libvirt do |lv|
    #    lv.random_hostname = true
    #    lv.default_prefix = "lab"
        lv.storage_pool_name = "personal"
        lv.driver = "qemu"
        lv.qemu_use_agent = true
        lv.channel :type => "unix", :target_type => "virtio", :target_name => "org.qemu.guest_agent.0"
        lv.cpus = 1
        lv.memory = 1024
      end
    end
  end
  config.vm.provision "shell" do |s|
    ssh_pub = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      mkdir -p /home/vagrant/.ssh
      echo #{ssh_pub} >> /home/vagrant/.ssh/authorized_keys
      chown -R vagrant /home/vagrant
      chown -R vagrant /home/vagrant/.ssh/authorized_keys
      chmod 600 /home/vagrant/.ssh/authorized_keys
      echo 'fastestmirror=1' >> /etc/dnf/dnf.conf
      echo 'max_parallel_downloads=10' >> /etc/dnf/dnf.conf
    SHELL
  end
  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = "vagrant_libvirt_bootstrap.yml"
  # end
end
