---
# tasks file for epel
- name: Enable EPEL.
  ansible.builtin.dnf:
    name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts.distribution_major_version }}.noarch.rpm'
    disable_gpg_check: true
    state: present
