---
# https://briandumont.medium.com/building-a-libvirt-dynamic-inventory-for-ansible-automation-platform-b8cf130471f3
- name: Deploy DevStack standalone node.
  hosts: node1
  become: true
  tasks:
    - name: Enable EPEL.
      ansible.builtin.dnf:
        name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts.distribution_major_version }}.noarch.rpm'
        disable_gpg_check: true
        state: present

    - name: Install git
      ansible.builtin.dnf:
        name: git
        state: present

    - name: Clone DevStack repository.
      ansible.builtin.git:
        repo: https://opendev.org/openstack/devstack/
        dest: /opt/devstack
        version: stable/2025.1

    - name: Run stack user creation script.
      ansible.builtin.command: /opt/devstack/tools/create-stack-user.sh
      register: create_stack_user # <- Registers the command output.
      changed_when: create_stack_user.rc != 0 # <- Uses the return code to define when the task has changed.

    - name: Change ownership of DevStack files.
      ansible.builtin.file:
        path: /opt/devstack
        owner: stack
        group: stack
        recurse: true

    - name: Copy DevStack config for standalone mode.
      ansible.builtin.copy:
        src: files/local.conf
        dest: /opt/devstack/local.conf
        mode: preserve
        owner: stack
        group: stack
