---
name: Setup trusted zone
firewalld:
  zone: trusted
  source: 10.1.1.0/24
  permanent: yes
  state: enabled

name: Setup public zone
firewalld:
  zone: public
  service:
   - http
   - https
  permanent: yes
  state: enabled

name: Create whitelist ipset
shell:
  cmd: firewall-cmd --permanent --new-ipset=whitelist --type=hash:net --option=family=inet --option=hashsize=4096 --option=maxelem=200000     --set-description="An ipset list of networks permitted to access"

name: Add whitelist
shell:
  cmd: firewall-cmd --permanent --ipset=whitelist --add-entries-from-file=whitelist

name: Attatch whilelist ipset
shell:
  cmd: firewall-cmd --permanent --zone=public --add-source=ipset:whitelist

name: Setup drop zone
firewalld:
  zone: drop
  permanent: yes
  state: enabled
  icmp_block_inversion: yes

name: Create blacklist ipset
shell:
  cmd: firewall-cmd --permanent --new-ipset=blacklist --type=hash:net --option=family=inet --option=hashsize=4096 --option=maxelem=200000 --set-description="An ipset list of networks or ips to be dropped."

name: Add blacklist file
shell:
  cmd: firewall-cmd --permanent --ipset=blacklist --add-entries-from-file=blacklist

name: Attatch black ipset
shell:
  cmd: firewall-cmd --permanent --zone=drop --add-source=ipset:blacklist