---
virt_yum_green_list:
  - libvirt
  - qemu-kvm
  - virt-install
  - virt-viewer

virt_socket_list:
  - virtqemud.socket
  - virtqemud-ro.socket
  - virtqemud-admin.socket
  - virtnetworkd.socket
  - virtnetworkd-ro.socket
  - virtnetworkd-admin.socket
  - virtnodedevd.socket
  - virtnodedevd-ro.socket
  - virtnodedevd-admin.socket
  - virtnwfilterd.socket
  - virtnwfilterd-ro.socket
  - virtnwfilterd-admin.socket
  - virtsecretd.socket
  - virtsecretd-ro.socket
  - virtsecretd-admin.socket
  - virtstoraged.socket
  - virtstoraged-ro.socket
  - virtstoraged-admin.socket
  - virtinterfaced.socket
  - virtinterfaced-ro.socket
  - virtinterfaced-admin.socket

# virt_yum_red_list:
#   - ntp
#   - gnome-photos
#   - rhythmbox 
#   - totem
#   - cheese
#   - simple-scan
#   - gnome-weather
#   - gnome-maps