---
# tasks file for microshift
- name: Ensure CRI-O is installed.
  block:
#    - name: CRI-O "{{ crio_version }}" module is enabled.
#      shell:
#        cmd: dnf module enable -y cri-o:"{{ crio_version }}"
    - name: CRI-O and tools are installed.
      dnf:
        name:
          - cri-o
          - cri-tools
        state: present
    - name: Ensure CRI-O service is enabled and running.


- name: Ensure MicroShift is deployed.
  block:
    - name: MicroShift repo is enabled.
      shell:
        cmd: dnf copr enable -y @redhat-et/microshift
    - name: MicroShift is installed.
      dnf:
        name: microshift
        state: present
    - name: MicroShift service is enavled and running.
      systemd:
        name: microshift
        enabled: yes
        masked: no
        state: started

- name: Ensure Firewalld is configured.
  block:
  - name: Firewalld is installed.
    dnf:
      name: firewalld
      state: latest
  - name: Ensure Firewalld is running.
    systemd:
      name: firewalld
      enabled: yes
      masked: no
      state: started
  - name: Ensure ports are permited.
    firewalld:
      zone: public
      port: "{{ item }}"
      immediate: true
      permanent: true
      state: enabled
    with_items:
      - 80/tcp
      - 443/tcp
      - 5353/tcp
      - 6443/tcp
  - name: Ensure internal network is trusted.
    firewalld:
      zone: trusted
      source: 10.42.0.0/16
      immediate: true
      permanent: true
      state: enabled

#- name: Ensure OC CLI is installed
#- name: Ensure Kubeconfig is defined