---
- name: Configure the Apache HTTP Server
  hosts: web
  gather_facts: false
  tasks:
    - name: Gather subset facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - 'pkg_mgr'
          - 'service_mgr'
      tags:
        - always
        - install
        - setup

    - name: Ensure SELinux is disabled
      ansible.posix.selinux:
        state: disabled
      tags:
        - security
        - setup

    - name: Ensure Apache HTTP Server is installed
      ansible.builtin.package:
        name:
          - httpd
        state: present
      tags:
        - service
        - setup

    - name: Ensure web content directory is present
      ansible.builtin.file:
        path: "{{ web_custom_directory }}"
        state: directory
        mode: '0755'
        owner: apache
        group: apache
      tags:
        - setup
        - content

    - name: Ensure web content is present using copy
      ansible.builtin.copy:
        dest: /var/www/web/index.html
        content: echo "Hello! I'm {{ ansible_facts['nodename'] }}. This is a web server managed by Ansible!"
        mode: '0644'
        owner: apache
        group: apache
      changed_when: false
      become: true
      tags:
        - setup
        - content
      notify:
        - Restart HTTPD

    - name: Ensure proper configuration of the Apache HTTP Server
      ansible.builtin.lineinfile:
        dest: /etc/httpd/conf/httpd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        # validate: /usr/sbin/httpd -t
      loop:
        - regexp: '^Listen 80$'
          line: 'Listen {{ web_custom_port }}'
        - regexp: '^ServerAdmin root@localhost'
          line: 'ServerAdmin support@example.com'
        - regexp: '^DocumentRoot "/var/www/html"'
          line: 'DocumentRoot "/var/www/web"'
        - regexp: '^<Directory "/var/www/html">'
          line: '<Directory "{{ web_custom_directory }}">'
      tags:
        - setup
        - config
        - content
      notify:
        - cycle_web

    - name: Ensure Apache HTTP Server is running and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      tags:
        - service
        - setup

    - name: Ensure Firewalld Service is running and enabled
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
      tags:
        - security
        - setup

    - name: Ensure custom HTTP traffic is perimmitted in the default zone of firewalld
      ansible.posix.firewalld:
        port: "{{ web_firewall_port }}"
        state: enabled
        permanent: true
        immediate: true
      tags:
        - security
        - setup
      notify:
        - Restart Firewalld
        - cycle_web

  handlers:
    - name: Restart HTTPD
      ansible.builtin.service:
        name: httpd
        state: restarted
      listen: cycle_web

    - name: Restart Firewalld
      ansible.builtin.service:
        name: firewalld
        state: restarted

    - name: Verify web content
      ansible.builtin.uri:
        url: http://{{ ansible_facts['nodename'] }}:{{ web_custom_port }}
        status_code: [200]
        return_content: true
      listen: cycle_web
