---
# tasks file for foreman
#- name: Install CentOS SCLo RH Testing repository
#  yum:
#    name: centos-release-scl-rh
#    state: present

- name: Enable Puppet 6 Repo
  yum:
    name: https://yum.puppet.com/puppet6-release-el-7.noarch.rpm
    state: present

- name: Enable EPEL Repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    disable_gpg_check: yes
    state: present

- name: Enable Foreman Repo
  yum:
    name: https://yum.theforeman.org/releases/2.1/el7/x86_64/foreman-release.rpm
    disable_gpg_check: yes
    state: present

- name: Install Foreman
  yum:
    name: [ foreman-installer ]
    update_cache: yes
    state: latest

#- name: Add local to hosts file.
#  shell: echo "10.1.1.252 foreman.lab.local" >> /etc/hosts

- name: Run foreman-installer.
  shell: foreman-installer

- name: Show Foreman credentials.
  shell: egrep "^foreman::params::initial_admin_(u|p)" /var/log/foreman-installer/foreman.log
  register: creds
