# ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
REQUIRED_PLUGINS = %w(vagrant-libvirt vagrant-hostsupdater vagrant-faster)
exit unless REQUIRED_PLUGINS.all? do |plugin|
  Vagrant.has_plugin?(plugin) || (
    puts "The #{plugin} plugin is required. Please install it with:"
    puts "$ vagrant plugin install #{plugin}"
    false
  )
end

nodes = [
  {:name => "kcn1", :cpus => 2, :memory => 2048, :storage => "4G"},
  {:name => "kwn1", :cpus => 2, :memory => 2048, :storage => "100G"}
]

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # config.vm.box = "centos/stream9"
  # config.vm.box = "fedora/41-cloud-base"
  # config.ssh.insert_key = false
  nodes.each do |node|
    config.vm.define "#{node[:name]}" do |deploy|
      deploy.vm.hostname = "#{node[:name]}"
      deploy.vm.network :public_network, :dev => "br0"
      deploy.vm.provider :libvirt do |domain|
        domain.mgmt_attach = false
        domain.uri = "qemu+ssh://evan@10.1.1.200/system"
        domain.default_prefix = "talos-"
        domain.management_network_name = "public"
        domain.cpus = "#{node[:cpus]}"
        domain.memory = "#{node[:memory]}"
        domain.qemu_use_agent = true
        domain.channel :type => "unix", :target_name => "org.qemu.guest_agent.0", :target_type => "virtio"
        # domain.serial :type => "file", :source => {:path => "/tmpkcn1.log"}
        domain.storage :file, :device => :cdrom, :path => "/var/lib/libvirt/storage/software/talos-metal-amd64.iso", :readonly => true
        domain.storage :file, :size => "#{node[:storage]}", :type => "qcow2"
        domain.boot 'hd'
        domain.boot 'cdrom'
      end
    end
  end
end