all:
  children:
    db:
      hosts:
        database-server-a:
          ansible_ssh_host: db1
    web:
      hosts:
        web-server-a:
          ansible_ssh_host: wb1
      vars:
        ansible_become: true
        ansible_user: vagrant
